@startuml
title Просмотр и редактирование запаса

actor Пользователь as user
participant Приложение as client

user -> client: Нажимает на запас в списке
user <-- client: Открывает форму запаса с текущими данными
user -> client: Меняет название или состояние, нажимает «Сохранить»
client -> client: Сохраняет изменения на устройстве
user <-- client: Закрывает форму, показывает список с обновленными данными

alt Альтернативный сценарий 1: закрытие формы без сохранения
user -> client: Нажимает на запас в списке
user <-- client: Открывает форму запаса с текущими данными
user -> client: При необходимости вносит изменения, нажимает кнопку закрытия формы (✕)
user <-- client: Закрывает форму без сохранения изменений, показывает список запасов
end alt

alt Альтернативный сценарий 2: изменение значений в блоке «дополнительно»
user -> client: Нажимает на запас в списке
user <-- client: Открывает форму запаса с текущими данными
user -> client: Нажимает «дополнительно»
user <-- client: Показывает все дополнительные поля запаса
user -> client: Меняет значения дополнительных полей, нажимает «Сохранить»
client -> client: Сохраняет изменения на устройстве
user <-- client: Закрывает форму, показывает список с обновленными данными
end alt
@enduml
