@startuml
title Просмотр и фильтрация всех запасов

actor Пользователь as user
participant Приложение as client

user -> client: Выбирает фильтр по состоянию, по категории или оба фильтра
user <-- client: Показывает только запасы, которые соответствуют выбранным фильтрам

alt Альтернативный сценарий 1: сброс фильтра
user -> client: Выбирает фильтр по состоянию, по категории или оба фильтра
user <-- client: Показывает только запасы, которые соответствуют выбранным фильтрам
user -> client: Нажимает кнопку сброса фильтра по состоянию или кнопку «Все» для сброса категории
user <-- client: Сбрасывает фильтр, обновляет список запасов
end alt

alt Альтернативный сценарий 2: нет запасов с выбранными фильтрами
user -> client: Выбирает фильтр по состоянию, по категории или оба фильтра
client -> client: Не находит запасов, которые соответствуют выбранным фильтрам
user <-- client: Показывает сообщение, что запасов с выбранными фильтрами нет
end alt
@enduml
