@startuml

title Поиск по названию запаса

actor Пользователь as user

participant Приложение as client

database "Хранилище на устройстве" as storage

user -> client: Вводит название запаса в поле поиска

client -> storage: Запрашивает запасы\nпо введенному названию

storage --> client: Возвращает найденный запас\nили список подходящих запасов

client --> user: Показывает запас\nили список подходящих запасов

opt Сброс поиска
    user -> client: Нажимает кнопку сброса поиска
    client -> storage: Запрашивает все запасы
    storage --> client: Возвращает все запасы
    client --> user: Показывает все запасы
end

@enduml